# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GitVersion.SemVer: ''

steps:
- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false
  displayName: gitversion

- task: RegexReplace@3
  inputs:
    InputSearchPattern: '/package.json'
    FindRegex: '"version":\s*"(\d+\.\d+\.\d+)"'
    ReplaceRegex: '$(GitVersion.SemVer)'
    UseUTF8: true
    UseRAW: true

- task: RegexReplace@3
  inputs:
    InputSearchPattern: '/package.json'
    FindRegex: '_@vsix@_'
    ReplaceRegex: './jungeriusit.jungit-winservices-$(GitVersion.SemVer).vsix'
    UseUTF8: true
    UseRAW: true

- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'vss-extension.json'
    FindRegex: '"version":\s*"(\d+\.\d+\.\d+)"'
    ReplaceRegex: '$(GitVersion.SemVer)'
    UseUTF8: true
    UseRAW: true

- task: RegexReplace@3
  inputs:
    InputSearchPattern: '**\task.json'
    FindRegex: '"Major":\s*"(\d+)"'
    ReplaceRegex: '$(GitVersion.Major)'
    UseUTF8: true
    UseRAW: true

- task: RegexReplace@3
  inputs:
    InputSearchPattern: '**\task.json'
    FindRegex: '"Minor":\s*"(\d+)"'
    ReplaceRegex: '$(GitVersion.Minor)'
    UseUTF8: true
    UseRAW: true
    
- task: RegexReplace@3
  inputs:
    InputSearchPattern: '**\task.json'
    FindRegex: '"Patch":\s*"(\d+)"'
    ReplaceRegex: '$(GitVersion.Patch)'
    UseUTF8: true
    UseRAW: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm version $(GitVersion.SemVer)
    npm run build
  displayName: 'npm install and build'

- publish: $(System.DefaultWorkingDirectory)/
  artifact: VsixPackage